# Generated by Django 6.0.2 on 2026-03-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=20, unique=True)),
                ("model", models.CharField(max_length=100)),
                (
                    "consumption",
                    models.FloatField(
                        help_text="Fuel consumption rate in miles per gallon"
                    ),
                ),
                ("max_range", models.FloatField(help_text="Maximum range in miles")),
                ("capacity", models.FloatField(help_text="Capacity in tons")),
                (
                    "total_truck_milage",
                    models.FloatField(help_text="Total mileage driven in miles"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trucks",
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
