# Generated by Django 6.0.2 on 2026-03-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='fuel_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='fueling_station',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
