# Generated by Django 6.0.2 on 2026-03-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dailyLogs", "0001_initial"),
        ("trucks", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_logs",
                to="trucks.truck",
            ),
        ),
        migrations.AddField(
            model_name="driving",
            name="daily_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drivings",
                to="dailyLogs.dailylog",
            ),
        ),
        migrations.AddField(
            model_name="driving",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drivings",
                to="users.driver",
            ),
        ),
        migrations.AddField(
            model_name="offduty",
            name="daily_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="off_duties",
                to="dailyLogs.dailylog",
            ),
        ),
        migrations.AddField(
            model_name="offduty",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="off_duties",
                to="users.driver",
            ),
        ),
        migrations.AddField(
            model_name="onduty",
            name="daily_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="on_duties",
                to="dailyLogs.dailylog",
            ),
        ),
        migrations.AddField(
            model_name="onduty",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="on_duties",
                to="users.driver",
            ),
        ),
        migrations.AddField(
            model_name="sleeperberth",
            name="daily_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sleeper_berths",
                to="dailyLogs.dailylog",
            ),
        ),
        migrations.AddField(
            model_name="sleeperberth",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sleeper_berths",
                to="users.driver",
            ),
        ),
    ]
